[package]
name = "dss-project"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = "1.12.0"
serde = "1.0.130"
serde_derive = "*"
serde_json = "1.0.68"
uuid = { version = "0.8.2", features = ["serde"] }
mimalloc = "0.1.22"
reqwest = { version = "0.11", features = ["blocking", "json"] }